import { NgModule } from "@angular/core";
import {DragDropModule} from '@angular/cdk/drag-drop';
import {ScrollingModule} from '@angular/cdk/scrolling';
import {CdkTableModule} from '@angular/cdk/table';
import {CdkTreeModule} from '@angular/cdk/tree';
import {MatButtonModule,
        MatFormFieldModule,
        MatInputModule, 
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatButtonToggleModule,
        MatCardModule,
        MatCheckboxModule,
        MatChipsModule,
        MatDatepickerModule,
        MatDialogModule,
        MatDividerModule,
        MatExpansionModule,
        MatGridListModule,
        MatIconModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSelectModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatSortModule,
        MatStepperModule,
        MatTableModule,
        MatTabsModule,
        MatTooltipModule,
        MatTreeModule} from '@angular/material';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';


@NgModule({
    imports: [DragDropModule,
              CdkTableModule,
              CdkTreeModule,
              MatFormFieldModule,
              MatInputModule,
              MatToolbarModule,
              MatIconModule,
              MatAutocompleteModule,
              MatBadgeModule,
              MatBottomSheetModule,
              MatButtonModule,
              MatButtonToggleModule,
              MatCardModule,
              MatCheckboxModule,
              MatChipsModule,
              MatDatepickerModule,
              MatDialogModule,
              MatDividerModule,
              MatExpansionModule,
              MatGridListModule,
              MatIconModule,
              MatInputModule,
              MatListModule,
              MatMenuModule,
              MatNativeDateModule,
              MatPaginatorModule,
              MatProgressBarModule,
              MatProgressSpinnerModule,
              MatRadioModule,
              MatRippleModule,
              MatSelectModule,
              MatSidenavModule,
              MatSliderModule,
              MatSlideToggleModule,
              MatSnackBarModule,
              MatSortModule,
              MatStepperModule,
              MatTableModule,
              MatTabsModule,
              MatToolbarModule,
              MatTooltipModule,
              MatTreeModule,
              ScrollingModule,
              NgbModule.forRoot()],
    exports: [DragDropModule,
              CdkTableModule,
              CdkTreeModule,
              MatButtonModule,
              MatFormFieldModule,
              MatInputModule,
              MatToolbarModule,
              MatIconModule,
              MatListModule,
              MatAutocompleteModule,
              MatBadgeModule,
              MatBottomSheetModule,
              MatButtonModule,
              MatButtonToggleModule,
              MatCardModule,
              MatCheckboxModule,
              MatChipsModule,
              MatDatepickerModule,
              MatDialogModule,
              MatDividerModule,
              MatExpansionModule,
              MatGridListModule,
              MatInputModule,
              MatMenuModule,
              MatNativeDateModule,
              MatPaginatorModule,
              MatProgressBarModule,
              MatProgressSpinnerModule,
              MatRadioModule,
              MatRippleModule,
              MatSelectModule,
              MatSidenavModule,
              MatSliderModule,
              MatSlideToggleModule,
              MatSnackBarModule,
              MatSortModule,
              MatStepperModule,
              MatTableModule,
              MatTabsModule,
              MatToolbarModule,
              MatTooltipModule,
              MatTreeModule,
              ScrollingModule,
              NgbModule],
              providers: []
})
export class MaterialModule{}